name    'ehazlett-graylog2'
version '0.0.2'
source ''
author 'ehazlett'
license 'Apache License, Version 2.0'
summary 'Installs and configures Graylog2 centralized logger'
description ''
project_page 'https://github.com/ehazlett/puppet-module-graylog2'